In [56]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [57]:
Idle = pd.read_csv('../Idle.csv')
Gesture = pd.read_csv('../Gesture.csv')

In [58]:
print(Idle.head())
print(Idle.shape[0])
print(Idle.shape[1])

     Ax    Ay    Az    Gx    Gy    Gz
0  0.03 -0.01  0.97  0.07  0.03 -0.03
1  0.03  0.00  0.97  0.07  0.03 -0.03
2  0.03  0.00  0.97  0.07  0.03 -0.03
3  0.03  0.00  0.98  0.07  0.03 -0.03
4  0.03  0.01  0.97  0.07  0.02 -0.03
1281
6


In [59]:
print(Gesture.head())
print(Gesture.shape[0])
print(Gesture.shape[1])

     Ax    Ay    Az    Gx    Gy    Gz
0 -0.01 -1.02  0.15  0.08  0.00  0.05
1 -0.01 -1.02  0.16  0.11  0.02 -0.00
2 -0.03 -1.03  0.18  0.05  0.04 -0.02
3 -0.00 -1.00  0.17  0.08 -0.02 -0.05
4 -0.02 -1.01  0.16 -0.03  0.05 -0.00
1280
6


In [60]:
#dropping last row to match both datasets
Idle = Idle.drop(Idle.index[-1])
print(Idle.head())
print(Idle.shape[0])
print(Idle.shape[1])

     Ax    Ay    Az    Gx    Gy    Gz
0  0.03 -0.01  0.97  0.07  0.03 -0.03
1  0.03  0.00  0.97  0.07  0.03 -0.03
2  0.03  0.00  0.97  0.07  0.03 -0.03
3  0.03  0.00  0.98  0.07  0.03 -0.03
4  0.03  0.01  0.97  0.07  0.02 -0.03
1280
6


In [61]:
physical_gestures = 32
snapshots = 40
readings = 6
Idle = np.array(Idle)
Gesture = np.array(Gesture)

#converting to 3d matrix
Idle = Idle.reshape(physical_gestures, snapshots, readings)
Gesture = Gesture.reshape(physical_gestures, snapshots, readings)

print(Idle)
print(Idle.shape[0])
print(Idle.shape[1])

print(Gesture)
print(Gesture.shape[0])
print(Gesture.shape[1])

[[[ 0.03 -0.01  0.97  0.07  0.03 -0.03]
  [ 0.03  0.    0.97  0.07  0.03 -0.03]
  [ 0.03  0.    0.97  0.07  0.03 -0.03]
  ...
  [ 0.03  0.    0.97  0.07  0.03 -0.03]
  [ 0.03 -0.    0.97  0.07  0.02 -0.03]
  [ 0.03  0.    0.97  0.07  0.03 -0.03]]

 [[ 0.03  0.    0.97  0.07  0.03 -0.03]
  [ 0.03 -0.    0.97  0.07  0.02 -0.03]
  [ 0.02  0.    0.97  0.07  0.03 -0.03]
  ...
  [ 0.03 -0.    0.97  0.07  0.02 -0.03]
  [ 0.03 -0.    0.96  0.07  0.02 -0.03]
  [ 0.03 -0.    0.98  0.07  0.03 -0.03]]

 [[ 0.03  0.    0.97  0.07  0.02 -0.03]
  [ 0.03 -0.    0.98  0.07  0.02 -0.03]
  [ 0.03  0.01  0.97  0.07  0.03 -0.03]
  ...
  [ 0.03 -0.    0.97  0.07  0.02 -0.03]
  [ 0.03  0.    0.98  0.07  0.03 -0.03]
  [ 0.02 -0.    0.97  0.07  0.03 -0.03]]

 ...

 [[ 0.03 -0.    0.97  0.07  0.03 -0.03]
  [ 0.02  0.    0.98  0.07  0.03 -0.03]
  [ 0.03 -0.    0.97  0.07  0.03 -0.03]
  ...
  [ 0.03 -0.    0.97  0.07  0.03 -0.03]
  [ 0.03 -0.    0.99  0.07  0.03 -0.03]
  [ 0.03  0.01  0.98  0.07  0.02 -0.03]]

 [

In [62]:
#made targets for both sets
target_idle = np.zeros(32)
target_gesture = np.ones(32)

In [63]:
#joined both targets and sets along the x-axis just stacked on to of each other
X = np.concatenate((Idle, Gesture), axis = 0)
Y = np.concatenate((target_idle, target_gesture), axis = 0)

In [64]:
#shuffling these both in the same fashion
shuffled_indices = np.random.permutation(len(X))

X = X[shuffled_indices]
Y = Y[shuffled_indices]

In [67]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size = 0.2, random_state = 42, stratify = Y)

In [73]:
np.savez(
    'kinematic_dataset.npz', X_train = X_train, X_test = X_test, Y_train = Y_train, Y_test = Y_test)